jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      uses: malinskiy/action-android/install-sdk@release/0.1.6
    - continue-on-error: true
      run: ./gradlew build
name: CI
on:
  repository_dispatch:
    types: trigger-ga___CI.yml
