jobs:
  Espresso:
    continue-on-error: true
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      uses: malinskiy/action-android/install-sdk@release/0.1.6
    - continue-on-error: true
      uses: malinskiy/action-android/emulator-run-cmd@release/0.1.6
      with:
        abi: x86
        api: 29
        cmd: ./gradlew clean build connectedCheck
        tag: default
    - continue-on-error: true
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Espresso-report
        path: ./**/build/reports/androidTests/connected
name: Espresso
on:
  repository_dispatch:
    types: trigger-ga___Espresso.yml
